# Generated by Django 5.2.10 on 2026-02-28 15:52

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='sessionmaterial',
            name='file',
            field=models.FileField(blank=True, help_text='Upload files like PDF, PPTX, ZIP, etc.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='session_materials/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='task_attachments/'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='task_submissions/'),
        ),
    ]
