# Generated by Django 5.2.8 on 2026-01-26 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdm', '0003_paymentdocument_fee_payment_and_more'),
        ('trainer', '0002_lessonplan_certificate_exam_examresult_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('recording', 'Class Recording'), ('notes', 'Class Notes'), ('slides', 'Presentation Slides'), ('code', 'Code Files'), ('reference', 'Reference Material'), ('assignment', 'Assignment/Exercise'), ('other', 'Other')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, help_text='Upload files like PDF, PPTX, ZIP, etc.', null=True, upload_to='session_materials/%Y/%m/')),
                ('external_link', models.URLField(blank=True, help_text='YouTube, Google Drive, GitHub, etc.')),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration of video/recording', null=True)),
                ('video_platform', models.CharField(blank=True, help_text='YouTube, Vimeo, Google Drive, etc.', max_length=50)),
                ('is_mandatory', models.BooleanField(default=False, help_text='Must students view this?')),
                ('is_public', models.BooleanField(default=False, help_text='Visible to all or only enrolled students?')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='trainer.lessonsession')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to='bdm.trainer')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_accessed', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=1)),
                ('has_viewed', models.BooleanField(default=False)),
                ('has_downloaded', models.BooleanField(default=False)),
                ('watch_time_minutes', models.IntegerField(default=0, help_text='For video recordings')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_access', to='bdm.student')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='trainer.sessionmaterial')),
            ],
            options={
                'ordering': ['-last_accessed'],
                'unique_together': {('material', 'student')},
            },
        ),
    ]
