# Generated by Django 5.2.10 on 2026-01-27 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdm', '0003_paymentdocument_fee_payment_and_more'),
        ('trainer', '0003_sessionmaterial_materialaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_plans', to='bdm.course'),
        ),
    ]
