# Generated by Django 5.2.10 on 2026-01-21 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('duration', models.CharField(max_length=50)),
                ('tech_stack', models.TextField()),
                ('course_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('syllabus', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=200)),
                ('coding_languages', models.TextField()),
                ('frameworks', models.TextField()),
                ('bio', models.TextField(blank=True)),
                ('experience', models.IntegerField()),
                ('basic_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('mode', models.CharField(choices=[('remote', 'Remote'), ('offline', 'Offline')], default='offline', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('converted', 'Converted'), ('idle', 'Idle'), ('dropped', 'Dropped')], default='new', max_length=10)),
                ('enquiry_date', models.DateTimeField(auto_now_add=True)),
                ('last_followup', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'TELE-CALLER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('preferred_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdm.course')),
            ],
            options={
                'ordering': ['-enquiry_date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('education', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('coding_expertise', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=15)),
                ('payment_option', models.CharField(choices=[('emi', 'EMI'), ('advanced', 'Advanced Full Payment'), ('monthly', 'Monthly Payment')], max_length=15)),
                ('booking_fee_received', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('remote', 'Remote'), ('onsite', 'Onsite')], max_length=10)),
                ('preferred_batch_time', models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening'), ('full_day', 'Full Day')], max_length=10, null=True)),
                ('attendance_percentage', models.FloatField(blank=True, null=True)),
                ('task_score_sum', models.IntegerField(default=0)),
                ('join_date', models.DateField()),
                ('certificate_eligible', models.BooleanField(blank=True, null=True)),
                ('course_completion_status', models.CharField(choices=[('phase1', 'Phase 1'), ('phase2', 'Phase 2'), ('phase3', 'Phase 3'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='phase1', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('selected_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bdm.course')),
            ],
            options={
                'ordering': ['-join_date'],
            },
        ),
        migrations.CreateModel(
            name='TeleCallerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('department', models.CharField(default='Business Development', max_length=100)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_leads', models.IntegerField(default=0)),
                ('converted_leads', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('expected_finish_date', models.DateField()),
                ('duration_months', models.IntegerField()),
                ('requested_extension', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdm.course')),
                ('students', models.ManyToManyField(blank=True, related_name='batches', to='bdm.student')),
                ('trainers', models.ManyToManyField(blank=True, related_name='batches', to='bdm.trainer')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['-start_date'],
            },
        ),
    ]
