# Generated by Django 5.2.10 on 2026-02-02 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bdm', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdocument',
            name='fee_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='student.feepayment'),
        ),
        migrations.AddField(
            model_name='paymentdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentreminder',
            name='fee_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='student.feepayment'),
        ),
        migrations.AddField(
            model_name='paymentreminder',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdccollection',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_cheques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pdccollection',
            name='fee_payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pdc_details', to='student.feepayment'),
        ),
        migrations.AddField(
            model_name='student',
            name='selected_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bdm.course'),
        ),
        migrations.AddField(
            model_name='pdccollection',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdc_cheques', to='bdm.student'),
        ),
        migrations.AddField(
            model_name='paymentreminder',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_reminders', to='bdm.student'),
        ),
        migrations.AddField(
            model_name='onboardingchecklist',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_checklist', to='bdm.student'),
        ),
        migrations.AddField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='batches', to='bdm.student'),
        ),
        migrations.AddField(
            model_name='studentissue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentissue',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentissue',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='bdm.student'),
        ),
        migrations.AddField(
            model_name='telecallerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchschedule',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_slots', to='bdm.trainer'),
        ),
        migrations.AddField(
            model_name='batch',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='batches', to='bdm.trainer'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='batchschedule',
            unique_together={('batch', 'day_of_week', 'start_time')},
        ),
    ]
