# Generated by Django 5.2.10 on 2026-02-24 05:58

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdocument',
            name='document_file',
            field=models.FileField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='payment_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='pdccollection',
            name='cheque_image',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='pdc_cheques/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='students/'),
        ),
        migrations.AlterField(
            model_name='studentadminprofile',
            name='batch_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdm.batch'),
        ),
        migrations.AlterField(
            model_name='studentadminprofile',
            name='enrolled_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdm.course'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='trainers/'),
        ),
    ]
