# Generated by Django 5.2.10 on 2026-02-28 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdm', '0004_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='confirmed_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_leads', to='bdm.course'),
        ),
        migrations.AddField(
            model_name='lead',
            name='discussed_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='educational_qualification',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='interested_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_batches', to='bdm.batch'),
        ),
        migrations.AddField(
            model_name='lead',
            name='payment_plan',
            field=models.CharField(blank=True, choices=[('full', 'Full Payment'), ('installment', 'Installment'), ('emi', 'EMI'), ('pdc', 'PDC')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='telecaller_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_plan', models.CharField(blank=True, choices=[('full', 'Full Payment'), ('installment', 'Installment'), ('emi', 'EMI'), ('pdc', 'Post Dated Cheque')], max_length=20, null=True)),
                ('total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('admission_fee_paid', models.BooleanField(default=False)),
                ('admission_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_done', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='bdm.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='bdm.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='bdm.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
