# Generated by Django 5.2.10 on 2026-03-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdm', '0005_lead_confirmed_course_lead_discussed_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='admission_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='admission_fee_paid',
            field=models.BooleanField(default=False),
        ),
    ]
