# Generated by Django 5.2.10 on 2026-02-28 15:52

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentagreement',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='enrollment_agreements/'),
        ),
        migrations.AlterField(
            model_name='enrollmentagreement',
            name='payment_plan',
            field=models.CharField(choices=[('full', 'Full Payment'), ('emi', 'EMI'), ('pdc', 'PDC'), ('installment', 'Installment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Medical certificate, etc.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='leave_documents/'),
        ),
        migrations.AlterField(
            model_name='placementapplication',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='placement/offers/'),
        ),
        migrations.AlterField(
            model_name='placementapplication',
            name='resume_submitted',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='placement/applications/'),
        ),
        migrations.AlterField(
            model_name='placementprofile',
            name='resume',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='placement/resumes/'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='student_documents/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='studentidcard',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='id_cards/qr_codes/'),
        ),
    ]
